### ISSUE TITLE
`import <coroutine>` issue

### ISSUE THREAD

**Issue by cdacamar** [kelbon/kelcoro#1]
While looking through the source I noticed this:

```c++
// export import <coroutine>; MSVC BUG(breaks compilation)
```
in [include/kel_coro.ixx](https://github.com/kelbon/kelcoro/blob/main/include/kel_coro.ixx#L7).  What was the issue here and is there a compiler bug open for it?

**Comment by kelbon** [comment]
CL.exe -23452985498329

**Comment by kelbon** [comment]
![image](https://user-images.githubusercontent.com/58717435/155784393-21fc1123-517d-4d7e-a583-4614d2356d75.png)

**Comment by cdacamar** [comment]
This appears to be a compiler ICE.  Could I encourage you to open a bug about the problem: https://developercommunity.visualstudio.com/report?space=62&entry=problem

**Comment by kelbon** [comment]
> This appears to be a compiler ICE. Could I encourage you to open a bug about the problem: https://developercommunity.visualstudio.com/report?space=62&entry=problem

i already 2 times opened bug about it
